#!/usr/bin/env bash
# Check if there are enough arguments

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
# Assigning parameters for variables

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Disabling Srict host ket

scp -o "StrictHostKeyChecking=no" -i "path_to_ssh_key" "path_to_file" "username@ip:~/"

# Checking if file transfer was successfull

if [$? -eq 0]
then
	echo "FILE TRANSFER WAS SUCCESSFULLY CARRIED OUT"
else
	echo "FILE TRANSFER FAILED"
fi
